// docsIndex.js — índice de las docs sin JSX: lo comparten la página de docs
// (menú, título y descripción de cada sección) y el sitemap que genera Vite.
export const DOCS_INDEX = [
  { id: 'introduccion', group: 'Empezar', title: 'Introducción',
    description: 'Qué es lixbon: chat con modelos de IA sobre GPUs propias, desde la web, el CLI, la app de escritorio, Visuals o la API.' },
  { id: 'primeros-pasos', group: 'Empezar', title: 'Primeros pasos',
    description: 'Crea tu cuenta, envía tu primer mensaje, elige modelo y lleva lixbon a tu terminal o a tu editor.' },
  { id: 'chat', group: 'Aplicaciones', title: 'Chat web',
    description: 'Cómo funciona el chat de lixbon: modelos, razonamiento, adjuntos, dictado, búsqueda web, historial y enlaces públicos.' },
  { id: 'visuals', group: 'Aplicaciones', title: 'Visuals',
    description: 'Diseña landings, dashboards, emails, logos y prototipos con IA; edítalos en el lienzo, compártelos y conviértelos en proyecto.' },
  { id: 'cli', group: 'Aplicaciones', title: 'CLI',
    description: 'Instala el CLI de lixbon en Windows, Linux o macOS: chat en la terminal, modo agente, modo plan y todos los comandos.' },
  { id: 'desktop', group: 'Aplicaciones', title: 'App de escritorio',
    description: 'El IDE de lixbon: editor con autocompletado, chat y agente integrados, actualizaciones automáticas y canales estable y beta.' },
  { id: 'remote', group: 'Aplicaciones', title: 'Remote',
    description: 'Controla una sesión del CLI o del IDE desde el móvil o la web: transcript en vivo, nuevos prompts y aprobaciones.' },
  { id: 'api', group: 'Desarrolladores', title: 'API',
    description: 'API compatible con OpenAI: autenticación con API key, endpoint base, modelos y chat completions en streaming.' },
  { id: 'usar-api-key', group: 'Desarrolladores', title: 'Usar tu API key',
    description: 'Recetas para usar tu API key de lixbon con cURL, los SDK de OpenAI en Python y JavaScript, continue.dev y otras herramientas.' },
  { id: 'precios-api', group: 'Desarrolladores', title: 'Precios de la API',
    description: 'Tarifas por millón de tokens de cada modelo, cómo se calcula el costo y cómo funcionan los créditos prepago.' },
  { id: 'planes', group: 'Cuenta y pagos', title: 'Planes y límites',
    description: 'Gratuito, Pro y Advance: mensajes al día, tokens al mes, API keys, peticiones por minuto y cómo se cuentan los límites.' },
  { id: 'facturacion', group: 'Cuenta y pagos', title: 'Facturación y pagos',
    description: 'Cómo se cobra en lixbon: suscripción con tarjeta, cambio de plan prorrateado, cancelación, facturas, recargas y recarga automática.' },
  { id: 'privacidad', group: 'Cuenta y pagos', title: 'Privacidad y datos',
    description: 'Qué guarda lixbon, cómo exportar tus datos, borrar el historial o eliminar la cuenta, y qué pasa con tu tarjeta.' },
];
